### PR TITLE
scripts: export interrupt for macro use

### PR DESCRIPTION
**Pull request by orangecms**

### CODE REVIEW

**Comment by orangecms** [comment]
not sure if this is correct, please recheck

**Comment by andelf** [comment]
The interrupt definitions in svd files are not revised yet.
Currently, I'm trying to follow the stm32fxxx style of pac definition.
All chip variants will be split into different sub-mods when it's ready.

See-also: https://docs.rs/stm32f1/0.15.1/stm32f1/

The interrupt mod is under the chip's sub mod.

**Comment by orangecms** [comment]
How would I use it at the moment? Something like `use Interrupt as interrupt`?

**Comment by andelf** [comment]
Hi, I'm planing to close this.
After some digging into WCH's RISC-V architecture, I find that I need to rewrite a `-rt` crate for it. For that:

- It uses some special csr registers to handler interrupt
- It's actually re-introduced Cortex-M's interrupt vector to RISC-V(plain table of addresses, instead of jump instructions). And this is the default behaviour of WCH's official EVT code base.
- It has a hardware push for interrupt handlers

**Comment by andelf** [comment]
Currently I'm working on a toy implementation for WCH's special `-rt`. I'll update when it's available for early tests.

**Comment by andelf** [comment]
Close as ch32v-rt is created.

**Pull request closed without merging**
