### PR TITLE
Updating depending cargo creates: riscv and riscv-rt

### PR DESCRIPTION
**Pull request by nosuz**
Thank you for providing us greate peripherals accessing crates.

These crates are depending on some other crates, and some of them are updated.
I am trying to follow the latest version of riscv and riscv-rt cates.

But I have some troubles in `./script/generate.sh`. This command makes the next errors.

```
+ xmllint --schema svd/CMSIS-SVD.xsd --noout svd/fixed/ch32v103.svd.patched
svd/fixed/ch32v103.svd.patched:193: element enumeratedValues: Schemas validity error : Element 'enumeratedValues': Missing child element(s). Expected is one of ( name, headerEnumName, usage, enumeratedValue ).
svd/fixed/ch32v103.svd.patched:201: element enumeratedValues: Schemas validity error : Element 'enumeratedValues': Missing child element(s). Expected is one of ( name, headerEnumName, usage, enumeratedValue ).
svd/fixed/ch32v103.svd.patched:217: element enumeratedValues: Schemas validity error : Element 'enumeratedValues': Missing child element(s). Expected is one of ( name, headerEnumName, usage, enumeratedValue ).
svd/fixed/ch32v103.svd.patched:225: element enumeratedValues: Schemas validity error : Element 'enumeratedValues': Missing child element(s). Expected is one of ( name, headerEnumName, usage, enumeratedValue ).
<<SNIP>>
svd/fixed/ch32v103.svd.patched fails to validate
```

I use svd and svd2rust commands installed as follows.

```
# svd command
$ pip3 install --upgrade --user svdtools
# svd2rust
$ cargo install svd2rust
```

I am very happy if anyone give me some advices.

Tahnk you

### CODE REVIEW

**Comment by nosuz** [comment]
I think these errors ocure because  <enumeratedValues derivedFrom="*"> in SVD files are not expanded.

But enumeratedValues is enumerationType, and enumerationType has derivedFrom attribute.

line 428 in CMSIS-SVD.xsd
<xs:attribute name="derivedFrom" type="identifierType" use="optional"/>

**Review by andelf — APPROVED** [review]

**Comment by andelf** [comment]
Thanks. I'll check the errors later.

**Comment by andelf** [comment]
@nosuz ~~Never mind, `check-format.sh` is used to check the official svd files. The svd files WCH provided is very buggy.~~

I made a mistake. ch32v103's svd patch is refactored in #8, so it uses some advanced grammar for generating crates.
I commented out the xmlint line.

**Comment by nosuz** [comment]
Thank you for accepting my Pull-Request.

**Comment by andelf** [comment]
They are already released as the latest pac crates.
I'm currently working part-time on https://github.com/ch32-rs/ch32v20x-hal.

**Comment by nosuz** [comment]
As you know, the CH32V103 and CHV203 share most of the peripherals. And your hal can be extended for CH32V103.

I have forked your repository and am hoping to contribute. But I am a beginner to the Rust program and studying what's going on hals by writing my hal.

**Pull request merged**
